//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoList.Web.Resources.TasksPanel {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TasksPanelView_ru_RU {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TasksPanelView_ru_RU() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ToDoList.Web.Resources.TasksPanel.TasksPanelView_ru_RU", typeof(TasksPanelView_ru_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Tasks_not_planed {
            get {
                return ResourceManager.GetString("Tasks not planed", resourceCulture);
            }
        }
        
        internal static string Task_is_about_to_expire {
            get {
                return ResourceManager.GetString("Task is about to expire", resourceCulture);
            }
        }
        
        internal static string Delete_task {
            get {
                return ResourceManager.GetString("Delete task", resourceCulture);
            }
        }
        
        internal static string Create_task {
            get {
                return ResourceManager.GetString("Create task", resourceCulture);
            }
        }
    }
}
